"use client";

import { cx } from "@/components/ui/primitives";
import { useInView } from "@/components/ui/reveal";

export interface FlowStage {
  label: string;
  detail: string;
}

export const CORE_STAGES: FlowStage[] = [
  { label: "Operations", detail: "The everyday workflows of the organization." },
  {
    label: "ERP Data",
    detail: "Structured operational information generated by those workflows.",
  },
  {
    label: "Analytics & Signals",
    detail: "Metrics, trends, rules, thresholds, anomalies, and risk indicators.",
  },
  {
    label: "AI Intelligence",
    detail: "AI interprets the signals in organizational context.",
  },
  { label: "Insights", detail: "Clear explanations of what changed and why it matters." },
  {
    label: "Actions",
    detail: "Recommended next steps for people responsible for the operation.",
  },
];

/**
 * The signature NotifyHub architecture rail: operations resolve into data,
 * data into signals, signals into interpreted insight, insight into action.
 */
export function IntelligenceFlow({
  stages = CORE_STAGES,
  tone = "dark",
  className,
}: {
  stages?: FlowStage[];
  tone?: "dark" | "light";
  className?: string;
}) {
  const { ref, inView } = useInView<HTMLDivElement>({ threshold: 0.2 });
  const dark = tone === "dark";

  return (
    <div ref={ref} className={cx("w-full", className)}>
      {/* Desktop rail */}
      <div className="hidden lg:block">
        <div className="relative">
          {/* Connector */}
          <div
            aria-hidden
            className={cx(
              "absolute top-[26px] right-0 left-0 h-px",
              dark ? "bg-white/12" : "bg-ink-200",
            )}
          />
          <div
            aria-hidden
            className={cx(
              "absolute top-[26px] left-0 h-px origin-left transition-transform duration-[1600ms] ease-out motion-reduce:transition-none",
              dark
                ? "bg-gradient-to-r from-cobalt-500 via-cobalt-400 to-signal-500"
                : "bg-gradient-to-r from-cobalt-500 via-cobalt-400 to-signal-500",
            )}
            style={{
              width: "100%",
              transform: inView ? "scaleX(1)" : "scaleX(0)",
            }}
          />
          <div aria-hidden className="absolute top-[22px] right-0 left-0 h-[9px]">
            <span
              className={cx(
                "nh-travel-x absolute h-[9px] w-[9px] -translate-x-1/2 rounded-full",
                dark ? "bg-signal-300" : "bg-cobalt-500",
              )}
            />
          </div>

          <ol className="relative grid grid-cols-6 gap-5">
            {stages.map((stage, i) => (
              <li key={stage.label}>
                <div className="flex items-center gap-2">
                  <span
                    className={cx(
                      "nh-num flex h-[22px] w-[22px] items-center justify-center rounded-full border text-[11px] font-medium transition-colors duration-500",
                      dark
                        ? "border-white/20 bg-ink-950 text-ink-300"
                        : "border-ink-300 bg-white text-ink-600",
                    )}
                  >
                    {i + 1}
                  </span>
                  <span
                    aria-hidden
                    className={cx(
                      "h-px flex-1",
                      dark ? "bg-white/10" : "bg-ink-200",
                    )}
                  />
                </div>
                <h3
                  className={cx(
                    "mt-5 text-[15px] leading-tight font-semibold",
                    dark ? "text-white" : "text-ink-950",
                  )}
                >
                  {stage.label}
                </h3>
                <p
                  className={cx(
                    "mt-2 text-[13px] leading-relaxed",
                    dark ? "text-ink-400" : "text-ink-600",
                  )}
                >
                  {stage.detail}
                </p>
              </li>
            ))}
          </ol>
        </div>
      </div>

      {/* Tablet and mobile: vertical rail */}
      <ol className="relative lg:hidden">
        <span
          aria-hidden
          className={cx(
            "absolute top-2 bottom-2 left-[10px] w-px",
            dark ? "bg-white/12" : "bg-ink-200",
          )}
        />
        {stages.map((stage, i) => (
          <li key={stage.label} className="relative pb-7 pl-9 last:pb-0">
            <span
              className={cx(
                "nh-num absolute top-0 left-0 flex h-[21px] w-[21px] items-center justify-center rounded-full border text-[11px] font-medium",
                dark
                  ? "border-white/20 bg-ink-950 text-ink-300"
                  : "border-ink-300 bg-white text-ink-600",
              )}
            >
              {i + 1}
            </span>
            <h3
              className={cx(
                "text-[15px] leading-tight font-semibold",
                dark ? "text-white" : "text-ink-950",
              )}
            >
              {stage.label}
            </h3>
            <p
              className={cx(
                "mt-1.5 text-[13.5px] leading-relaxed",
                dark ? "text-ink-400" : "text-ink-600",
              )}
            >
              {stage.detail}
            </p>
          </li>
        ))}
      </ol>
    </div>
  );
}
